name=input("what is your name? ")
print(len(name))
print(name.lower())
print(name.upper())
print(name.find("a"))
print(name[-2])
print(name[0:])
print(name.find('ahmed'))
print(name.replace("ahmed", 'Rana Muhammad Ahmed Aziz'))
print('a' in name)
